package matchuri.backend.domain.realtime.entity;

public enum RealtimeEventType {
    REALTIME_CONNECTED,
    GROUP_INVITE_CREATED,
    GROUP_MEMBER_JOINED,
    GROUP_MEMBER_LEFT,
    GROUP_DELETED,
    GROUP_RECOMMENDATION_STARTED,
    GROUP_RECOMMENDATION_READINESS_UPDATED,
    GROUP_RECOMMENDATION_OPENED,
    GROUP_RECOMMENDATION_VOTE_UPDATED,
    GROUP_RECOMMENDATION_VOTE_COMPLETED,
    GROUP_RECOMMENDATION_FINALIZED
}
